export * from "./avatar"
export * from "./products"
export * from "./nodata"
export * from "./smileRating"
export { default as RewardCheckerPointChecker } from "./checkerpointChecker.svg"
export { default as LandingLeftImage } from "./landingleft.png"
export { default as LandingRightImage } from "./landingright.png"
export { default as FloatingLanding } from "./floatinglanding.png"
export { default as WhyChooseUs } from "./whychooseus.svg"
export { default as WhyChooseUsSmall } from "./whychooseussmall.svg"
export { default as ProfileRewards } from "./profileRewards.svg"
export { default as ProfileCompletion } from "./profileCompletion.svg"
export { default as DiscountCodeImg } from "./discountCode.svg"
export { default as CreateProductOffersImg } from "./createProductOffers.svg"
// export { default as CheckerSmallLogo } from "./Checker.png"
export { default as CoinCheckr } from "./Checker.png"
export { default as CheckerSmallLogo } from "./checkr_coin.png"