import Head from "next/head"
import Layout from "layout"
import { Button } from "components"
import { useFarmingContract } from "hooks/useFarmingContract"
import { useWallet } from "hooks/useWallet"
// import { useProductAirdropContract } from "hooks/useProductAirdropContract"

export default function FarmingTest() {
  const {
    startFarming,
    enterFarming,
    exitFarming,
    claimRewards,
    getFarmingState,
    calculateRemainingRewards,
    getStakedAmount,
    getNextRewardRemainingEpoch,
    setCurrentRound
  } = useFarmingContract()
  const { wallet } = useWallet()

  // const { getCurrentTime, getAirdrop } = useProductAirdropContract()
  return (
    <Layout>
      <Head>
        <title>Farming Test | CheckerChain</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="container h-100 mt-4 pb-3">
        <div className="merkle-root">
          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              startFarming()
            }}
          >
            start farming (adming only)
          </Button>
          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              enterFarming({
                amount: 10
              })
            }}
          >
            enter farming
          </Button>

          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              exitFarming({
                amount: 10
              })
            }}
          >
            exit farming
          </Button>

          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              claimRewards({})
            }}
          >
            claim farming
          </Button>

          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              calculateRemainingRewards(wallet.address)
            }}
          >
            get farming rewards
          </Button>

          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              getFarmingState()
            }}
          >
            get farming state
          </Button>

          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              getStakedAmount(wallet.address)
            }}
          >
            get staked amount
          </Button>

          {/* <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              getCurrentTime()
            }}
          >
            get current time
          </Button>

          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              getAirdrop(24)
            }}
          >
            get airdrop
          </Button> */}
          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              getNextRewardRemainingEpoch()
            }}
          >
            Next Reward Remaining Epoch
          </Button>
          <Button
            className="btn btn-primary mt-4"
            onClick={() => {
              setCurrentRound(1)
            }}
          >
            Set Current Round
          </Button>
        </div>
      </div>
    </Layout>
  )
}
